# Generated by Django 4.2.7 on 2023-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='other_income',
        ),
        migrations.RemoveField(
            model_name='income',
            name='yearly_salary',
        ),
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
