# Generated by Django 4.2.7 on 2023-11-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_expense_delete_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Essential', 'Essential'), ('Nonessential', 'Nonessential')], default='Essential', max_length=255),
        ),
    ]
