# Generated by Django 4.2.7 on 2023-11-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_expense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('Essential', 'Essential'), ('Nonessential', 'Nonessential')], default='Essential', max_length=255),
        ),
    ]
