# Generated by Django 4.2.7 on 2023-11-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile'),
        ('main_app', '0009_alter_income_category'),
    ]

    operations = [
    ]
