# Generated by Django 4.2.7 on 2023-11-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_0005_profile_0009_alter_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Earned', 'Earned'), ('Passive', 'Passive'), ('Portfolio', 'Portfolio')], default='Earned', max_length=255),
        ),
    ]
